[theme]
primaryColor = "#FFC107"
backgroundColor = "#F2F2F2"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A1A1A"
font = "sans serif"

[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[ui]
hideSidebarNav = false

[client]
showSidebarNavigation = true
toolbarMode = "minimal"
